import mongoose, { Schema } from "mongoose";

// MCQ Question schema (30 questions, 2 marks each = 60 marks)
const mcqQuestionSchema = new Schema({
  question: { type: String, required: true },
  options: [{ type: String, required: true }], // 4 options
  correctAnswer: { type: Number, required: true }, // Index of correct option (0-3)
  marks: { type: Number, default: 2 },
});

// Short Answer Question schema (10 questions, 4 marks each = 40 marks)
const shortAnswerQuestionSchema = new Schema({
  question: { type: String, required: true },
  expectedAnswer: { type: String, required: true }, // For Gemini to evaluate
  marks: { type: Number, default: 4 },
});

// Test Attempt schema - tracks user attempts
const testAttemptSchema = new Schema({
  testId: { type: Schema.Types.ObjectId, ref: "RoadmapTest", required: true },
  userId: { type: String, required: true },
  roadmapId: { type: String, required: true },
  
  // User's answers
  mcqAnswers: [{ type: Number }], // Array of selected option indices
  shortAnswers: [{ type: String }], // Array of short answer responses
  
  // Scoring
  mcqScore: { type: Number, default: 0 }, // Out of 60
  shortAnswerScore: { type: Number, default: 0 }, // Out of 40
  totalScore: { type: Number, default: 0 }, // Out of 100
  percentage: { type: Number, default: 0 },
  passed: { type: Boolean, default: false }, // true if >= 60%
  
  // Detailed scoring for short answers (from Gemini)
  shortAnswerScores: [{ 
    questionIndex: Number,
    marksAwarded: Number,
    feedback: String,
  }],
  
  // Timestamps
  startedAt: { type: Date, default: Date.now },
  submittedAt: { type: Date },
  
  // Admin can allow retry
  canRetry: { type: Boolean, default: false },
});

// Main Roadmap Test schema
const roadmapTestSchema = new Schema({
  roadmapId: { type: String, required: true, unique: true },
  roadmapTitle: { type: String, required: true },
  
  // Test details
  mcqQuestions: [mcqQuestionSchema], // 30 questions
  shortAnswerQuestions: [shortAnswerQuestionSchema], // 10 questions
  
  // Test settings
  duration: { type: Number, default: 30 }, // 30 minutes
  totalMarks: { type: Number, default: 100 },
  passingPercentage: { type: Number, default: 60 },
  
  // Generated by Gemini
  generatedAt: { type: Date, default: Date.now },
  
  // Auto-expire after 4 days to regenerate fresh questions
  expiresAt: { 
    type: Date, 
    default: () => new Date(Date.now() + 4 * 24 * 60 * 60 * 1000) // 4 days from now
  },
  
  // Admin can regenerate test
  lastRegeneratedBy: { type: String },
  lastRegeneratedAt: { type: Date },
}, {
  timestamps: true,
});

// Indexes for efficient queries
roadmapTestSchema.index({ roadmapId: 1 });
testAttemptSchema.index({ userId: 1, roadmapId: 1 });
testAttemptSchema.index({ testId: 1, userId: 1 });

// Clean up existing models to prevent OverwriteModelError
if (mongoose.models.RoadmapTest) {
  delete mongoose.models.RoadmapTest;
}
if (mongoose.models.TestAttempt) {
  delete mongoose.models.TestAttempt;
}

export const RoadmapTest = mongoose.models.RoadmapTest || mongoose.model("RoadmapTest", roadmapTestSchema);
export const TestAttempt = mongoose.models.TestAttempt || mongoose.model("TestAttempt", testAttemptSchema);
